### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by JoshHrach** [Ryu0118/XCContributeRank#6]
When following the install instructions, brew fails with the following output:

> remote: Repository not found.
fatal: repository 'https://github.com/ryu0118/homebrew-rank/' not found
Error: Failure while executing; `git clone https://github.com/ryu0118/homebrew-rank /opt/homebrew/Library/Taps/ryu0118/homebrew-rank --origin=origin --template=` exited with 128.

**Comment by Ryu0118** [comment]
Sorry! homebrew-rank was set to private.
I just made it public.

**Comment by JoshHrach** [comment]
Thank you! Works great now.
